# Generated by Django 4.0.6 on 2022-07-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='this is a prodcut for sale'),
        ),
    ]
