# Generated by Django 4.1 on 2022-08-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commit_test',
            field=models.CharField(default='ona', max_length=120),
            preserve_default=False,
        ),
    ]
